"""add timestamps

Revision ID: 37290f49fba4
Revises: 73a07717bd05
Create Date: 2026-07-14 14:57:27.558584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "37290f49fba4"
down_revision: Union[str, Sequence[str], None] = "73a07717bd05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # COMMENTS
    op.add_column(
        "comments",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "comments",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("""
        UPDATE comments
        SET created_at = NOW(),
            updated_at = NOW()
        WHERE created_at IS NULL
    """)

    op.alter_column("comments", "created_at", nullable=False)
    op.alter_column("comments", "updated_at", nullable=False)

    # SUBTASKS
    op.add_column(
        "subtasks",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "subtasks",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("""
        UPDATE subtasks
        SET created_at = NOW(),
            updated_at = NOW()
        WHERE created_at IS NULL
    """)

    op.alter_column("subtasks", "created_at", nullable=False)
    op.alter_column("subtasks", "updated_at", nullable=False)

    # TASKS
    op.add_column(
        "tasks",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tasks",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("""
        UPDATE tasks
        SET created_at = NOW(),
            updated_at = NOW()
        WHERE created_at IS NULL
    """)

    op.alter_column("tasks", "created_at", nullable=False)
    op.alter_column("tasks", "updated_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "updated_at")
    op.drop_column("tasks", "created_at")
    op.drop_column("subtasks", "updated_at")
    op.drop_column("subtasks", "created_at")
    op.drop_column("comments", "updated_at")
    op.drop_column("comments", "created_at")
    # ### end Alembic commands ###
