"""sync models with db

Revision ID: 40fe708ec0c7
Revises: 6c5cf0bc66b1
Create Date: 2026-05-26 13:34:32.149428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fe708ec0c7'
down_revision: Union[str, Sequence[str], None] = '6c5cf0bc66b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('backlog', 'todo', 'in_progress', 'in_review', 'qa', 'completed', name='statusenum'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('backlog', 'todo', 'in_progress', 'in_review', 'qa', 'completed', name='statusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('backlog', 'todo', 'in_progress', 'in_review', 'qa', 'completed', name='statusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('subtasks', 'status',
               existing_type=sa.Enum('backlog', 'todo', 'in_progress', 'in_review', 'qa', 'completed', name='statusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
